name: Docker Image CI for GHCR
on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.organization }} --password-stdin

      - name: Build and push the image
        run: |
          docker build -t ghcr.io/${{ github.organization }}/backend:latest --file Dockerfile .
          docker push ghcr.io/${{ github.organization }}/backend:latest
